# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gw < Formula
  desc "Git worktree wrapper with lifecycle hooks"
  homepage "https://github.com/gin0606/gw"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gin0606/gw/releases/download/v0.6.0/gw_0.6.0_darwin_amd64.tar.gz"
      sha256 "2de8bb468c528a2b2cc40afd1eb3a88bec2636c7697fe42d12d5f654fe1a5e1b"

      define_method(:install) do
        bin.install "gw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gin0606/gw/releases/download/v0.6.0/gw_0.6.0_darwin_arm64.tar.gz"
      sha256 "ba4b95cdaa795c6647d8305bb0e616c1da0f810a9e037ceeee8eb2697cac1bdc"

      define_method(:install) do
        bin.install "gw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gin0606/gw/releases/download/v0.6.0/gw_0.6.0_linux_amd64.tar.gz"
      sha256 "93965ddd4ee1da0774d6038ceda23994ef0348e2d5daaf90eba4c5da4fa2f9d8"
      define_method(:install) do
        bin.install "gw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gin0606/gw/releases/download/v0.6.0/gw_0.6.0_linux_arm64.tar.gz"
      sha256 "7ef9885d1a6167d791d344a113c0ae13029a4a2d98eed571500669c7a53d6c42"
      define_method(:install) do
        bin.install "gw"
      end
    end
  end
end
