# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gw < Formula
  desc "Git worktree wrapper with lifecycle hooks"
  homepage "https://github.com/gin0606/gw"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gin0606/gw/releases/download/v0.4.0/gw_0.4.0_darwin_amd64.tar.gz"
      sha256 "81d9f4e02376659e06ef2ee28426502dc771325d1df0ba2cd5b8f7c4fe1288a5"

      def install
        bin.install "gw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gin0606/gw/releases/download/v0.4.0/gw_0.4.0_darwin_arm64.tar.gz"
      sha256 "7cc4e9746e6f6adbefe686aea8b1f76c19ef1e3f8ff5103860f1b434a144144a"

      def install
        bin.install "gw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gin0606/gw/releases/download/v0.4.0/gw_0.4.0_linux_amd64.tar.gz"
      sha256 "ffea3cc6797ee8804c42e22fa921d995eb51f697992ddaa0abb8e0808f9bacfd"
      def install
        bin.install "gw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gin0606/gw/releases/download/v0.4.0/gw_0.4.0_linux_arm64.tar.gz"
      sha256 "79c07dc112e534a97419fce9b79dab2e8f0b37126dc1bd8c5021e8b3dfda93ab"
      def install
        bin.install "gw"
      end
    end
  end
end
